# Generated by Django 3.0.6 on 2020-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('pin_code', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CartQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(default='', max_length=50)),
                ('Aachar', models.IntegerField(default=0)),
                ('Papad', models.IntegerField(default=0)),
                ('P_C', models.IntegerField(default=0)),
                ('K_M_G', models.IntegerField(default=0)),
                ('Lemonade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='images/shop')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(default='', max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='ecommerce.Product')),
                ('qty', models.ManyToManyField(to='ecommerce.CartQty')),
            ],
        ),
    ]
